require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '14.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'voice_discussion_app' do
  use_native_modules!

  use_react_native!(
    :path => "../node_modules/react-native",
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNSpeech', :path => '../node_modules/@react-native-community/voice'

  target 'voice_discussion_appTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      "../node_modules/react-native",
      :mac_catalyst_enabled => false,
    )
  end
end
